package com.example.android.landlayapplication;

import java.util.ArrayList;

/**
 * Created by Android on 9/26/2017.
 */

public class BookSet {
    private static BookSet bookSet;
    private static ArrayList<Book> bookList = new ArrayList<Book>();

    private BookSet() {
        //populate the ArrayList
        bookList.add(new Book("Emma", "Beautiful, clever, rich—and single—Emma Woodhouse is perfectly content with her life and sees no need for either love or marriage. Nothing, however, delights her more than interfering in the romantic lives of others. But when she ignores the warnings of her good friend Mr. Knightley and attempts to arrange a suitable match for her protégée, Harriet Smith, her carefully laid plans soon unravel and have consequences that she never expected. With its imperfect but charming heroine and its witty and subtle exploration of relationships, Emma is often seen as Jane Austen’s most flawless work.", R.drawable.janeaustene, "Emma Woodhouse has the world at her fingertips. She’s young, pretty, and smart; she also happens to be the reigning queen of her village’s social scene. Emma lives in Highbury, a small town about sixteen miles outside of London, with her aging father. Mr. Woodhouse loves Emma, but he’s utterly unable to offer her any guidance – which is perhaps why Emma doesn’t seem to have any sense of her own limitations. Life seems pretty sweet – if a bit boring – and so Emma decides to spice things up by taking on a protégé, Harriet Smith. Even though Emma’s determined never to marry herself, she immediately decides to find Harriet a husband.\n\n" +
                "Determined to make Harriet into a gentlewoman, Emma sets out to refine Harriet’s tastes – especially in men. She convinces Harriet to dump Robert Martin, the young farmer who likes her, and set her sights on the town’s clergyman, Mr. Elton. Unfortunately, Mr. Elton turns out to be in love with Emma – or at least with Emma’s money. After the Mr. Elton debacle, Emma thinks that she’s learned her lessons in matchmaking. Luckily for us (if not for Harriet), she hasn’t.\n\n" +
                "When the dashing Frank Churchill comes to town, Emma tries very hard to fall in love with him herself. She can’t seem to fall head over heels for him, but she does manage to make a good deal of mischief by flirting with him in front of Jane Fairfax, a young woman who recently returned to Highbury to live with her aunts. Meanwhile, Emma decides that Frank might just be the perfect new man for Harriet.\n\n" +
                "Emma’s exploits are watched – and commented upon – by her good friend, Mr. Knightley. Although Emma frequently ignores his advice, she cherishes his good opinion. When Mr. Knightley accuses her of belittling her poor neighbors, Emma begins to reflect upon her mistakes and even starts to change her ways.\n\n" +
                "Unfortunately, Harriet confesses that she loves Mr. Knightley, not Frank. All of a sudden, Emma’s plans crumble. She realizes that she loves Mr. Knightley too. Convinced that Mr. Knightley might be interested in Harriet, despite the fact that he practically lives with the Woodhouses, Emma crushes Mr. Knightley’s attempts to propose to her. Eventually all romantic muddles are cleared: Emma marries Mr. Knightley, and Harriet marries her farmer, Robert Martin.\n\n" +
                "Emma’s story is surrounded by side-narratives of life in Highbury, including the romance of Frank and Jane Fairfax, the marriage of Emma’s former governess, Mrs. Weston, and the escapades of the social climbers, Mr. and Mrs. Elton."));
        bookList.add(new Book("Sense and Sensibility", "Marianne Dashwood wears her heart on her sleeve, and when she falls in love with the dashing but unsuitable John Willoughby she ignores her sister Elinor's warning that her impulsive behaviour leaves her open to gossip and innuendo. Meanwhile Elinor, always sensitive to social convention, is struggling to conceal her own romantic disappointment, even from those closest to her. Through their parallel experience of love - and its threatened loss - the sisters learn that sense must mix with sensibility if they are to find personal happiness in a society where status and money govern the rules of love.", R.drawable.janeaustenss, "In the wake of their father's death, the Dashwood sisters, Elinor, Marianne, and Margaret, are left at the financial mercy of John, half-brother, and his greedy wife. Though their father asked John to take care of the girls and their distraught mother, the women end up getting seriously shafted – they're turned out of their family home, and basically left with a barely-respectable income to live on. \n\n" +
                "Left to their own devices, the ladies decide to move away to a cottage owned by a distant cousin in Barton Park, Devonshire. Before they move house, though, Elinor (the more practical sister) tentatively allows herself to fall in love with Edward Ferrars, the gentle brother of the girls' obnoxious sister-in-law. However, both of these young people are on the, shall we say, cautious side of the emotional spectrum, and the romance doesn't go anywhere. The Dashwood girls move away to their new home, leaving Edward behind.\n\n" +
                "In Devonshire, they find themselves in the company of the aforementioned cousin, Sir John Middleton, and his rather oddball family, comprised of a dully proper wife and a hilariously raucous mother-in-law, Mrs. Jennings. Also present is Sir John's good friend, Colonel Brandon, a thirty-something, somewhat stodgy, but good-hearted bachelor, who falls for young Marianne's girlish charms. The Dashwoods try make themselves at home in the cottage, but can't help but miss their childhood home. Marianne (the less-than-practical sister) is particularly blue – that is, until she develops a love interest of her own, a dashing young man named Willoughby. Everyone gets along with the new guy just swimmingly, and the whole family expects that Marianne and Willoughby will announce their engagement any day. Marianne is sure that she's found her soul mate.\n\n" +
                "Things start to go wrong fairly soon, though. Willoughby leaves rather suddenly for London, for reasons we're not entirely certain of, and doesn't give any indication of when he'll be back. Marianne takes this very hard, as she does everything. The plot continues to thicken with the arrival of an unexpected visitor – Edward Ferrars. He stays with his friends for a week, and all the while, everyone has a great time, even morose Marianne. However, Edward's departure heralds the arrival of another set of visitors, Mrs. Palmer, Lady Middleton's hyperactive sister, and her dour husband, Mr. Palmer. The Palmers just happen to live in the general vicinity of Willoughby's country home, and Marianne is eager for news of him – but there isn't any.\n\n" +
                "After the Palmers' departure, yet another wave of newcomers washes in… and this time, they're unwelcome ones. Mrs. Jennings invites some unknown relations of hers, Miss Steele and her younger sister, Lucy, to come and stay at Barton Park. To cut a long story short, Lucy Steele admits to Elinor that she's secretly engaged – to Edward Ferrars! Elinor is shocked and upset, and her hopes for the future all crumble before her eyes.\n\n" +
                "Both Dashwood sisters are now down in the dumps with regards to romance. At this low point, Mrs. Jennings asks Elinor and Marianne to accompany her to London for an extended trip, and after some squabbling, the girls accept. They embark upon their journey with mixed feelings – Marianne hoping to see Willoughby, and Elinor afraid that she'll run into Edward. Both of these things come to pass, but not in ways that the girls expect.\n\n" +
                "Willoughby avoids Marianne like the plague, despite many, many letters from her. When they finally meet at a ball (by accident), he evades her once again. Soon thereafter, Marianne receives a rather cold letter of dumpage from Willoughby, and she falls ill with the shock. Colonel Brandon, still carrying a torch for Marianne, is concerned, but also relieved – he finally tells Elinor the horrible truth about Willoughby, which he'd been concealing all along, thinking that Willoughby and Marianne were engaged. It turns out that Willoughby is a real cad; he got Colonel Brandon's adopted daughter pregnant, dumped her, and now is engaged to a super-wealthy socialite instead of Marianne.\n\n" +
                "Meanwhile, Elinor is forced to endure the company of her unwitting enemy, Lucy Steele, who's also in town. It seems that everyone is around – even the Dashwoods' brother, John, and sister-in-law Fanny (sister of Edward). To make matters even worse, Elinor finds out that Fanny and Edward's mother has decided that Edward must marry an heiress, a certain Miss Morton. It seems like nothing is going right for poor Elinor, but she tries to keep her emotions in check. However, Lucy and Edward's engagement comes to light, much to the dismay of pretty much everyone involved. The Ferrars are all in a fit about it, and Edward is in serious trouble. Distraught, Elinor eventually confesses everything to Marianne – that she's in love with Edward, but she's known for months about the secret engagement. Marianne instantly realizes that she's been too harsh on her sister; she used to berate Elinor for being too logical, but she sees now how much her older sis has been suffering.\n\n" +
                "It emerges that Edward has been cut out of the family fortune for his disobedient conduct, and that all of the money that was supposed to come his way has been given to his obnoxious younger brother, Robert. The sympathetic Colonel Brandon helps out by offering the young man a job as the curate at his estate, Delaford. It seems as though things have worked out for Edward and Lucy (though not ideally). \n\n" +
                "Disgruntled, the Dashwoods and Mrs. Jenkins leave town, and head out to the Palmers' country house, Cleveland. The party hangs out there for a while, but Marianne can't help but be upset by their proximity to Willoughby's ancestral home, Combe Magna. She catches a cold wandering around outside, and quickly becomes dangerously ill.\n\n" +
                "Everyone's in crisis mode because of Marianne's frightening illness – apparently, even Willoughby. He shows up, disheveled and distraught, having heard that Marianne is at death's door. He opens his heart to Elinor, explaining that the only reason he married someone else was because of money – basically, he screwed up a lot of things (namely, his relationship with Colonel Brandon's adopted daughter), and his mistakes ended up preventing him from marrying Marianne, his true love. He leaves, after being reassured that Marianne's on the mend. Elinor finally forgives him (kind of) for his dastardly deeds, and knows that this story will make Marianne feel better. Elinor and Marianne's mother arrives shortly thereafter, with dramatic news of her own: Colonel Brandon has confessed that he's in love with Marianne, and Mrs. Dashwood already regards their engagement as a foregone conclusion.\n\n" +
                "Marianne slowly gets better in the company of her mother, sister, and friends, and finally, the little family heads back home to Barton, where Elinor tells Marianne and her mother about Willoughby's true feelings. Everyone feels something akin to resolution, at long last. Elinor, however, is unsettled anew by a report that \"Mr. Ferrars\" is married to Lucy Steele. Happily, though, there turns out to be a miscommunication; the Mr. Ferrars in question is Robert, the younger brother, not Edward. Elinor receives this good news from Edward himself, who comes to finally ask her to marry him (yay!). In the end, that little minx, Lucy, managed to ingratiate herself with the new heir to the Ferrars fortune, and broke off her engagement with the no-longer-wealthy Edward. \n\n" +
                "In the end, everything works out – Lucy gets her rich husband, and Elinor gets the man she loves. Finally, Marianne finds her own happiness, too – she learns to love Colonel Brandon back, and the pair is married. After all the drama, both Elinor and Marianne end up with their happy endings."));
        bookList.add(new Book("Mansfield Park", "Taken from the poverty of her parents' home in Portsmouth, Fanny Price is brought up with her rich cousins at Mansfield Park, acutely aware of her humble rank and with her cousin Edmund as her sole ally. During her uncle's absence in Antigua, the Crawford's arrive in the neighbourhood bringing with them the glamour of London life and a reckless taste for flirtation. Mansfield Park is considered Jane Austen's first mature work and, with its quiet heroine and subtle examination of social position and moral integrity, one of her most profound.", R.drawable.janeaustenmp, "Mansfield Park is about a poor young girl named Fanny Price.\n\n" +
                "Born in Portsmouth, Fanny's mother has two sisters, one of whom has married Sir Thomas Bertram of Mansfield Park miles away and the other lives in a cottage on the grounds of Mansfield. This other sister, in an attempt to show off her own sense of self-importance and charity, offers to take one of her poor sister's children off her hands, and persuades Sir Thomas that Fanny could be her assistant in helping with the daily running of Mansfield and so should live there too.\n\n" +
                "At Mansfield Park, Fanny grows up with her cousins Tom, Maria, Julia and Edmund Bertram. Only Edmund is kind to her. As they grow up, Edmund's kindness to Fanny makes her fall in love with him.\n\n" +
                "However, when Fanny's uncle goes away for business, Mary Crawford and her brother Henry come to the neighborhood. Henry flirts with the Misses Bertram, making them fall in love with him, even though Maria is already engaged to a Mr. Rushworth. Mary and Edmund fall in love with each other, much to Fanny's surprise and sadness, but Mary wants Edmund to become rich and not be a clergyman. They put on a play called Lovers Vows that Fanny does not think Sir Thomas would like, so she does not join in. Just as they are trying to make her act, Sir Thomas returns home.\n\n" +
                "Henry Crawford goes away, and Maria, angry and proud, quickly marries Mr. Rushworth, even though she does not love him. Henry Crawford falls really in love with Fanny, and proposes to her, but she says no. Sir Thomas gives Fanny the ultimatum of marry Mr Crawford or go back to her parents. Choosing to see her family again she is unhappy to see how coarse and vulgar they are.\n\n" +
                "While she is there, she finds out in a newspaper that Maria has run away with Henry Crawford. Fanny is very shocked and unhappy. Edmund comes to ask Fanny to come back to Mansfield to nurse a sick Tom. He tells Fanny that he was shocked that Mary Crawford only thought Maria and Henry were silly for being found out, and that the act of adultery was not bad. He expresses he has finally realised he has always loved Fanny, and they marry."));
        bookList.add(new Book("Northanger Abbey", "During an eventful season at Bath, young, naïve Catherine Morland experiences the joys of fashionable society for the first time. She is delighted with her new acquaintances: flirtatious Isabella, who shares Catherine's love of Gothic romance and horror, and sophisticated Henry and Eleanor Tilney, who invite her to their father's mysterious house, Northanger Abbey. There, her imagination influenced by novels of sensation and intrigue, Catherine imagines terrible crimes committed by General Tilney. With its broad comedy and irrepressible heroine, this is the most youthful and and optimistic of Jane Austen's works.", R.drawable.janeaustenna, "A seventeen-year-old girl, Catherine Morland, travels with her rich relatives, Mr. and Mrs. Allen, to Bath in England. Innocent and inexperienced, Catherine Morland is a plump country girl with no friends in the city. At first, she is disappointed, because she does not have anyone to dance with at the ball. Then she meets an exciting gentleman, Mr. Tilney. She falls in love with him, but the next day, he has disappeared. She is upset and sad. Then she meets a flirtatious girl named Isabella. This makes her happier. She does not yet know all the evil intentions of her new friend.\n\n" +
                "Isabella introduces Catherine to the fun of reading gothic novels. But Catherine believes they are true. She does not understand the difference between reality and fiction. Then she is introduced to Isabella's brother John Thorpe, who finds himself falling in love with her. He thinks Catherine likes him too. Catherine then meets Henry Tilney again, and is introduced to Miss Tilney, his sister. She is a sensible, intelligent lady, who is much different from Isabella. Catherine also meets Miss Tilney's father, General Tilney.\n\n" +
                "Isabella joyfully tells Catherine of her engagement to Catherine's brother, James Morland. Later, John Thorpe proposes to Catherine, but she does not realise he is asking her to marry him. Later, when Isabella tells her that John is in love with her, she is really surprised and says no immediately. Then Eleanor Tilney invites Catherine to Northanger Abbey. Catherine there learns that the gothic novels are wrong, and that Northanger Abbey is a perfectly normal place, and is not haunted.\n\n" +
                "Catherine listens to General Tilney's conversations, and suspiciously thinks that perhaps he has murdered his wife, because he avoids talking about her. She persuades Eleanor Tilney to take her to Mrs. Tilney's room, but when General Tilney comes, she rushes away in fear. Catherine later goes again, but this time is found by Henry Tilney. She accidentally reveals her suspicions to Henry, who does not get angry at her. Then, running to her room crying, she is worried that Mr. Tilney does not like her any more. Later, Eleanor Tilney takes her to an open stage coach to immediately go home. Catherine is frightened and surprised, and thinks it is all because of her mistaken thoughts of General Tilney and his wife. When she goes home, she is sullen and quiet.\n\n" +
                "Henry Tilney then visits her house and asks her to marry him, even though General Tilney said no. He explains that at first, John Thorpe, who had thought Catherine would marry him soon, had lied to General Tilney that she was rich. General Tilney then tries to make her marry Henry, but later met John Thorpe again, after Catherine had said she would not marry him. He angrily tells General Tilney another lie, that Catherine is penniless. General Tilney, horrified, rudely made Catherine go home. Catherine's parents say they have to wait until General Tilney says yes.\n\n" +
                "Finally, Eleanor marries a charming man who is very rich, and this makes the General so happy he says that Henry can marry Catherine. Later, he finds out Catherine is not as poor as he had thought, so he is even happier. At last, Catherine and Henry are married."));
        bookList.add(new Book("Persuasion", "At twenty-\u00ADseven, Anne Elliot is no longer young and has few romantic prospects. Eight years earlier, she had been persuaded by her friend Lady Russell to break off her engagement to Frederick Wentworth, a handsome naval captain with neither fortune nor rank. What happens when they encounter each other again is movingly told in Jane Austen's last completed novel. Set in the fashionable societies of Lyme Regis and Bath, Persuasion is a brilliant satire of vanity and pretension, but, above all, it is a love story tinged with the heartache of missed opportunities.", R.drawable.janeaustenp, "Sir Walter is forced to stop spending so much money. Therefore, he decides to let his house to Admiral Croft and move to Bath for a while. Anne goes to stay with Mary. Anne discovers that Mrs. Croft, Admiral Croft's wife, is Captain Wentworth's sister. He is introduced to the Musgrove family. He has made much money, and is now a very desirable husband. When he and Anne meet, Anne feels deeply unhappy. He does not seem to care any more about her. He flirts with the two Musgrove sisters. Most people think that he will marry one of them.\n\n" +
                "They all go to visit Lyme Regis, where Wentworth's friend Captain Harville is staying. Captain Harville had been mourning for his sister, who died young, and comforting Captain Benwick, who had been engaged to marry her. In Lyme, Louisa Musgrove falls from the Cobb while playing with Captain Wentworth on the steps and is seriously injured. Captain Wentworth feels very guilty, and realizes everyone thinks he will marry her if she becomes well again.\n\n" +
                "Anne joins her father and sister in Bath. They are both being flattered by a widow, Mrs. Clay, the daughter of their family lawyer. William Elliot joins the family. Lady Russell encourages his attentions to Anne, but Anne feels unsure about him. Suddenly, news comes that Louisa is better, and that she and Benwick are engaged.\n\n" +
                "Wentworth appears in Bath, and becomes jealous of Mr. Elliot. Wentworth believes that Anne and Mr. Elliot are engaged to be married. However, Anne did not answer Mr. Elliot's marriage proposal. She later learns from an old friend, Mrs. Smith, that Mr. Elliot is a bad person. Mr. Elliot is afraid that Sir Walter and Mrs. Clay will have a son, who would then inherit Sir Walter's land. Mr. Elliot wants to marry Anne because he is attracted to her, but also make Mrs. Clay his mistress. Anne is shocked by this news.\n\n" +
                "Anne and Captain Harville talk about love, and whether women or men love for a longer time. After hearing them talk about this, Wentworth writes a letter to Anne. He tells Anne that he still loves her, and asks her to marry him again. She joyously says yes."));
        bookList.add(new Book("Pride and Prejudice", "Few have failed to be charmed by the witty and independent spirit of Elizabeth Bennet in Austen’s beloved classic Pride and Prejudice. When Elizabeth Bennet first meets eligible bachelor Fitzwilliam Darcy, she thinks him arrogant and conceited; he is indifferent to her good looks and lively mind. When she later discovers that Darcy has involved himself in the troubled relationship between his friend Bingley and her beloved sister Jane, she is determined to dislike him more than ever. In the sparkling comedy of manners that follows, Jane Austen shows us the folly of judging by first impressions and superbly evokes the friendships, gossip and snobberies of provincial middle-class life. ", R.drawable.janeaustenpp, "The story starts with Mr. Bingley, a wealthy, handsome young gentleman, who comes to town and rents a place near the Bennet family. He comes with quiet Mr. Darcy and his pretty sisters. Jane Bennet and Mr. Bingley begin to spend a lot of time with each other, even though the sisters of Mr. Bingley try to cut the attraction. Mr. Bingley is loved and admired by almost every woman in the town. Mr. Darcy is disliked by everybody, because of his arrogant way of talking and his mean attitude. Elizabeth Bennet, the second daughter of Mrs. Bennet, seems to despise Mr. Darcy. She despises him even more after he refused to dance with her at the ball.\n\n" +
                "Elizabeth soon grows to admire an officer named Wickham. He seems to equally hate Mr. Darcy. He tells her a sad story about how Mr. Darcy was mean to him. This story makes Elizabeth hate Mr. Darcy even more. Meanwhile, Mr. Darcy begins to fall in love with Elizabeth.\n\n" +
                "Bingley slowly begins to declare his proposal of marriage to Jane, when he suddenly has to leave to Netherfield. Netherfield is the house he lives at most of the time. He did not plan to leave for a long time but his sisters use this chance to move Bingley and Jane away from each other. The sisters follow Bingley to London. Bingley's quick leave makes Jane sad and confused. Elizabeth finds out that it is because of his sisters.\n\n" +
                "Before Mr. Bingley leaves, Mr. Collins, the man who was supposed to inherit all of Longbourn (where the Bennet family lives), appears. The rich and pompous Lady Catherine de Bourgh had employed him as a clergyman. Collins wanted to find a good wife from the daughters of Mr. Bennet. He tries to take Jane as his wife, but after learning about the relationship between her and Mr. Bingley, he tries to marry Elizabeth. He proposes, but Elizabeth rejects him. Her mother is angry because Elizabeth could have lived in Longbourn if she married Mr. Collins. Then Mr. Collins turns his attention to Elizabeth's friend, Charlotte Lucas. He decides to marry Charlotte. They marry and Charlotte invites Elizabeth over to her house for a short visit.\n\n" +
                "Elizabeth goes to Charlotte's house in the Spring. It is quite close to Rose Park. Rose Park is Lady Catherine de Bourgh's land. Mr. Darcy's aunt is Lady Catherine de Bourgh. He is staying there when Elizabeth visits and they meet. Elizabeth finds out that Mr. Darcy was the one who put an end to Mr. Bingley and Jane's love. She later rejects Mr. Darcy's proposal. She says all the mean thoughts she had about his cruelness towards Wickham and Jane and Mr. Bingley's relationship.\n\n" +
                "Darcy writes an explanation to Elizabeth in a letter. Mr. Wickham almost eloped with Darcy's 15 year old sister, Georgianna. Mr. Wickham had only wanted her money. Also, Darcy told Bingley not to propose marriage to Jane because he thought that she did not actually love him. Elizabeth returns home soon after and thinks about Darcy's explanations and all her misunderstandings about him.\n\n" +
                "A few months later, Elizabeth visits Pemberly during her tour with her aunt and uncle. Pemberly is Darcy's land. Mr. Darcy meets them there. and is very kind to them during their visit. Mr. Darcy's kindness makes Elizabeth even more attracted to him. She also becomes friends with his sister Georgianna. Later, Elizabeths receives a letter from Jane. It contains sad news that their younger sister Lydia, has run off with Wickham. They find out that Wickham does not want to marry Lydia, but this would cause a scandal. Elizabeth and her uncle and aunt hurriedly return home. Elizabeth thinks that now Mr. Darcy will never speak to her again because of her sister's behavior.\n\n" +
                "Then, Lydia and Wickham are found and are married. They later visit Longbourn. While describing her wedding to Elizabeth, Lydia talks about Mr. Darcy. Elizabeth sends an inquiry to her aunt because she is surprised. She learns that Mr. Darcy had paid for all the wedding expenses and paid Wickham to marry Lydia.\n\n" +
                "Bingley and Darcy come to Longbourn. Bingley proposes to Jane, and she accepts. Mr. Darcy proposes to Elizabeth, even though Lady Catherine does not like Elizabeth. Elizabeth accepts the proposal. Jane and Elizabeth marry their lovers on the same day"));
    }

    public static BookSet getBookSet() {
        //return new phone book

        if (bookSet == null)
        {
            bookSet = new BookSet();
        }
        return bookSet;
    }

    public ArrayList getItems(){
        return bookList;
    }

}
